### ISSUE TITLE
Aggiungere evento WordPress Meetup Bologna Novembre

### ISSUE THREAD

**Issue by PaoloLaurenti** [BolognaTechScene/bolognatechscene.github.io#67]
https://www.meetup.com/it-IT/WordPress-Meetup-Bologna/events/235439083/?eventId=235439083&from=ref

**Comment by phra** [comment]
lo stavo facendo adesso! LOL

**Comment by PaoloLaurenti** [comment]
Dura la vita dei contrbutors in pausa pranzo! :-D :-D

Ahahaha

A posto, già fatto.
Grazie comunque
  P.
